import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { LoginPage } from "./auth/login";
import { useSelector } from "react-redux";
import { Account } from "./auth/profile/[name]";

export default function Home() {
  const isSignedIn = useSelector((state) => state.userSession);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <div className={styles.grid}>
          <a className={styles.card}>
            {isSignedIn.loginStatus ? <Account /> : <LoginPage />}
          </a>
        </div>
      </main>
    </div>
  );
}
